//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_VACANTE
    {
        public int id { get; set; }
        public string Compañia { get; set; }
        public string Tipo { get; set; }
        public string Posicion { get; set; }
        public string Ubicacion { get; set; }
        public string Categoria { get; set; }
        public string Descripcion_Trabajo { get; set; }
        public string Como_Aplicar { get; set; }
        public string Email { get; set; }
    }
}
